### ISSUE TITLE
Monero Wallet is corrupted on Mac

### ISSUE THREAD

**Issue by Stevefunky** [jollheef/cryptocurrency#9]
Hi,
I'm afraid that I have no coding skills. I have a problem with my monero wallet. It appears to have become corrupted. When I try to open it on my mac I get the following message:

You can’t open the application “monero-wallet-gui 07.49.48” because it may be damaged or incomplete.

I have the .keys file but stupidly not the seed words or private key. If there is a way to recover my wallet I would be grateful for some help. I have downloaded the latest version of the wallet and tried to import the .keys file. When I select "Open a wallet from file. Import an existing .keys file from your computer on the next page I am offered two options.  1. A file icon with my wallet name and Mainnet 2. Browse file system. When I select the first option I am asked for my password which I enter and then get the message "Couldn't open wallet. No device found". If I browse the file system and select my .keys file I get the same result. I would appreciate any help that you could offer me on this to recover my wallet. Thanks

**Comment by jollheef** [comment]
Hello,

This is not a support forum for Monero Wallet.

⟶ [r/Monero](https://www.reddit.com/r/Monero)
